config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get  "/help", to: "static_pages#help"
    get  "/about", to: "static_pages#about"
    get  "/contact", to: "static_pages#contact"
    get  "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get  "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: %i(index create destroy)
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true,
            length: {maximum: Settings.Post.content_size}
  validate  :picture_size

  scope :micropost_desc, ->{order created_at: :desc}
  scope :feed, (lambda do |user|
    where user_id: user.id
  end)

  mount_uploader :picture, PictureUploader

  private

  def picture_size
    return unless picture.size > Settings.Post.size_image.megabytes
    errors.add(:picture, t("microposts.controller.size_image_content"))
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i(create destroy)
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build micropost_params

    if @micropost.save
      flash[:success] = t(".micro.created")
      redirect_to root_url
    else
      @feed_items = []
      flash[:danger] = t(".micro.nocreated")
      render "static_pages/home"
    end
  end

  def destroy
    if @micropost.destroy
      flash[:success] = t("microposts.controller.delete")
      redirect_to request.referer || root_url
    else
      flash[:danger] = t("microposts.controller.undelete")
      redirect_to request.referer
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit :content, :picture
  end

  def correct_user
    @micropost = current_user.microposts.find_by id: params[:id]
    redirect_to root_url if @micropost.blank?
  end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: Settings.Post.avatar_size), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    <%= t "microposts.micro.post_ago" %>  <%= time_ago_in_words micropost.created_at %>
    <% if current_user.current_user? micropost.user %>
<%= link_to t("users.destroy.delete"), microposts_path, method: :delete,
            data: { confirm: t("users.index.sure") } %>
    <% end %>
  </span>
</li>